[package]
name = "splinter"
version = "0.0.0"
description = "A Rust tokenizer library."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors = ["The splinter authors"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
memchr = { workspace = true }
rustc-hash = { workspace = true }
unicode-normalization = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
proptest = { workspace = true }
tempfile = { workspace = true }
serde_json = { workspace = true }
criterion = "0.8"