[package]
name = "splinter-cli"
version = "0.0.0"
description = "CLI for the splinter tokenizer library."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors = ["The splinter authors"]

[[bin]]
name = "splinter"
path = "src/main.rs"

[dependencies]
splinter = { path = "../../crates/splinter" }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }